-- M5: Generalize the thumbnails table into a multi-profile design_documents
-- table so non-thumbnail agents (detail-page, etc.) can share storage. The
-- column renames and kind discriminator keep YouPD's existing rows intact.

-- Rename the main table.
alter table public.thumbnails rename to design_documents;

-- Rename indexes / constraint so future migrations target the new names.
alter index if exists idx_thumbnails_org_candidate
  rename to idx_design_documents_org_candidate;
alter index if exists idx_thumbnails_updated_at
  rename to idx_design_documents_updated_at;
alter table public.design_documents
  rename constraint thumbnails_aspect_check to design_documents_aspect_check_legacy;

-- New columns.
alter table public.design_documents
  add column if not exists kind text;
update public.design_documents set kind = 'thumbnail' where kind is null;
alter table public.design_documents
  alter column kind set not null,
  alter column kind set default 'thumbnail';

alter table public.design_documents
  add column if not exists canvas jsonb;
update public.design_documents
  set canvas = case
    when aspect = '9:16' then jsonb_build_object('width', 720, 'height', 1280)
    else jsonb_build_object('width', 1280, 'height', 720)
  end
  where canvas is null;
alter table public.design_documents alter column canvas set not null;

-- aspect column kept for the thumbnail profile (Notion AI prompt
-- vocabulary). Future non-thumbnail profiles will leave it null and rely on
-- canvas alone, so drop the NOT NULL constraint.
alter table public.design_documents
  alter column aspect drop not null;

-- New indexes.
create index if not exists idx_design_documents_kind
  on public.design_documents (kind);

-- Rename the snapshot table + its FK column.
alter table public.thumbnail_versions rename to design_document_versions;
alter table public.design_document_versions
  rename column thumbnail_id to document_id;
alter index if exists idx_thumbnail_versions_thumbnail_version
  rename to idx_design_document_versions_doc_version;

-- The FK constraint name auto-generated by the original CREATE TABLE
-- references the old table; rename for symmetry.
do $$
begin
  if exists (
    select 1 from pg_constraint where conname = 'thumbnail_versions_thumbnail_id_fkey'
  ) then
    alter table public.design_document_versions
      rename constraint thumbnail_versions_thumbnail_id_fkey
      to design_document_versions_document_id_fkey;
  end if;
end $$;

-- Recreate RLS policies on the renamed tables (deny-all keeps current
-- security posture; app reads/writes go through service-role).
drop policy if exists "deny_all" on public.design_documents;
create policy "deny_all" on public.design_documents
  for all to anon, authenticated using (false) with check (false);

drop policy if exists "deny_all" on public.design_document_versions;
create policy "deny_all" on public.design_document_versions
  for all to anon, authenticated using (false) with check (false);

-- Add the canvas/kind-aware check to replace the strict aspect enum check.
alter table public.design_documents
  drop constraint if exists design_documents_aspect_check_legacy;
alter table public.design_documents
  add constraint design_documents_kind_check
  check (kind in ('thumbnail','detail-page'));
